<?xml version="1.0" encoding="utf-8"?><Database Name="MedSCAN_DB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=C:\Users\Nini\Documents\GitHub\MedSCAN2014\MS_Project1\MedSCAN_DB.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="MedSCANLibrary.Properties.Settings" SettingsPropertyName="MedSCAN_DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Patient" Member="Patients">
    <Type Name="Patient">
      <Column Name="PatientID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lastname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="middleInit" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="gender" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="pregnant" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="photo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="allergies" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="scheduledMed_IDs" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PRNMed_IDS" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="physician" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="comments" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>